version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: electron
    versions:
    - ">= 8.2.a, < 8.3"
  - dependency-name: electron
    versions:
    - ">= 8.a, < 9"
  - dependency-name: sass-loader
    versions:
    - 10.1.1
    - 11.0.0
  - dependency-name: "@vue/cli-plugin-router"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.11
  - dependency-name: electron-builder
    versions:
    - 22.9.1
  - dependency-name: discord-rpc
    versions:
    - 3.1.4
