name: Build/release/ubuntu

on: push

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          node-version: 10
      - run: yarn install
      - run: yarn run electron:generate-icons
      - run: mkdir -p "dist_electron/@kubecraft"
      - run: yarn run publish -l
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: dist_electron
          path: dist_electron
